name: Run docker push image
description: Run docker push image
inputs:
  docker_image:
    description: "Docker image"
    required: false
    default: ""
  username:
    description: "Docker username"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: |
        docker tag ${{inputs.docker_image}} ${{inputs.username}}/ ${{inputs.docker_image}}
        docker push ${{inputs.username}}/ ${{inputs.docker_image}}
      shell: bash